version: '3'
services:
  gas-setup:
    restart: always
    build: .
    env_file:
      - ../.env
    container_name: gas-setup
    image: gas-setup
    tty: true
    volumes:
      - ../src:/root/opt